name = "pinequest-api"
main = "src/index.ts"
compatibility_date = "2026-03-24"

[[d1_databases]]
binding = "DB"
database_name = "pinequest-db"
database_id = "182994a1-0ed4-4db3-ae94-b192d71d50d0"
migrations_dir = "migrations"

[[r2_buckets]]
binding = "IMAGE_UPLOADS"
bucket_name = "pinequest-uploads"

[[durable_objects.bindings]]
name = "LIVE_EXAM_EVENTS"
class_name = "LiveExamEvents"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["LiveExamEvents"]
