name = "pinequest-api-dev"
main = "src/index.ts"
compatibility_date = "2026-03-24"

[[d1_databases]]
binding = "DB"
database_name = "pinequest-season2-preview"
database_id = "f7e393fb-fead-4253-8d0c-f3f234228d3d"
migrations_dir = "migrations"

[[r2_buckets]]
binding = "IMAGE_UPLOADS"
bucket_name = "pinequest-uploads-preview"

[[durable_objects.bindings]]
name = "LIVE_EXAM_EVENTS"
class_name = "LiveExamEvents"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["LiveExamEvents"]
